name: product-catalog-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go 1.22
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build Application
        run: |
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go

      - name: Run Unit Tests
        run: |
          cd src/product-catalog
          go test ./...

  code-quality:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SonarScanner CLI
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: Run SonarQube Analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
            -Dsonar.sources=src/product-catalog \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        id: docker_build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }} -f src/product-catalog/Dockerfile src/product-catalog

      - name: Save Image Name
        run: echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.run_id }}" >> $GITHUB_ENV

  trivy-scan:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Scan
        id: trivy_scan
        continue-on-error: true  # This prevents pipeline failure but captures exit code
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/Library/Caches:/root/.cache/ \
            aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL ${{ env.IMAGE_NAME }}

      - name: Check Scan Result
        run: |
          if [[ $? -ne 0 ]]; then
            echo "Trivy scan failed. Stopping workflow."
            exit 1
          fi

  push-docker:
    runs-on: ubuntu-latest
    needs: trivy-scan
    if: success()  # Push image only if Trivy scan was successful
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}

  updatek8s:
    runs-on: ubuntu-latest
    needs: push-docker
    if: success()  # Update Kubernetes manifests only if Docker push was successful
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}|" kubernetes/productcatalog/deploy.yaml

      - name: Commit and Push Manifest Changes
        run: |
          git config --global user.email "${{ secrets.GIT_AUTHOR_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI]: Update product-catalog image tag"
          git push origin HEAD:main -f
